### ISSUE TITLE
incorrect app updates count

### ISSUE THREAD

**Issue by ghost** [Aptoide/aptoide-client#18]
aptiode# 8.0.1.2 [ 8109 ]
device#/manufacturer: ls-4001/lyf
os# 5.1 aosp

all apps are either downloaded from app publisher [ if available ] or from other websites.

after the installation of the client, it is showing incorrect updates count.

i have enabled & disabled option: filter updates. but the issue is persistent.

i have few other queries:

[~] does all the apps downloaded by client has signatures ?

[*] if the signature of my existing app is different from client app signature, does the client notifies me that an update is available, even though both apps are same version ?

[*] if i update my existing app with client signed app [ same version ], does the client removes the existing app including settings or it will update the app with new signature ?

herewith are the URL for screenshots:

[~] http://m.imgur.com/aRjXB2F
[~] http://m.imgur.com/CMwWa9A

**Comment by henriquedesousa** [comment]
I have the same issue. In my case, it's due to the OS not allowing broadcast listeners, because I even have uninstalled apps showing as having updates. A simple fix is to add code to really refresh all apps when we do a "pull to refresh" in the updates fragment.

**Comment by henriquedesousa** [comment]
Glad to know you followed my advice and that the new version is now refreshing the updates just fine when doing a manual swipe-to-refresh. Many thanks Aptoide team!

**Comment by FredericoSantinho** [comment]
You're welcome my friend! :D
Lol
