### ISSUE TITLE
Translation: Help to find strings in project

### ISSUE THREAD

**Issue by ldmpub** [Aptoide/aptoide-client#20]
Hi,

Sometime I see part of app not translated or with errors. Is there an easy way to find these strings in Weblate to translate or change them?

For instance I can not find (despite several searches in all Weblate components) the following string which is still in english:
![screenshot_20170114-100226](https://cloud.githubusercontent.com/assets/1452146/21954247/e296909c-da4b-11e6-909a-8ee6a2eb9eb1.png)

Thanks for your help,

**Comment by ldmpub** [comment]
An other example:
![screenshot_20170114-095853](https://cloud.githubusercontent.com/assets/1452146/21954280/bc421032-da4c-11e6-8bd1-d7a9d56318c5.png)

**Comment by ldmpub** [comment]
Last example:
![screenshot_20170114-100017](https://cloud.githubusercontent.com/assets/1452146/21954393/9df4ec6e-da4f-11e6-9192-83f4e1bc62de.png)

**Comment by analaragomes** [comment]
In version v8.3.0.0, this is fixed.

Thanks.
