### ISSUE TITLE
Malicious translator on Weblate

### ISSUE THREAD

**Issue by ghost** [Aptoide/aptoide-client#23]
Dear Aptoide devs, there is a user (CTOUCH Europe) uploading extremely poor quality Dutch translations to the Aptoide translation efforts on Weblate, both new translations and changes in old translations. Please remove and ban this user from the project as soon as possible as there is no easy way to keep track of what they're changing and reverting those changes.

**Comment by jdandrade** [comment]
Hello, 
Thank you for the warning. 
We will investigate this issue. 

Best regards, 
JA

**Comment by ghost** [comment]
Thanks for looking into it. Upon closer look there may actually not be malicious intent as they also uploaded good translations (mostly for single words), but they did change several existing translations for the worse.

**Comment by AptRute** [comment]
Hello d9h02f,

Thank you for getting in touch. CTouch Europe is an Aptoide partner. We will investigate the issue nonetheless and see what we can do to ensure the quality of the translation/localization remains high.

Cheers,
Rute
