### ISSUE TITLE
Feature request: disable updates from unsubscribed stores

### ISSUE THREAD

**Issue by CarbonFixer** [Aptoide/aptoide-client#4]
Older versions of aptoide used to notify of updates only if you are subscribed to the store with the newer version. The latest aptoide client notifies of updates regardless of weather you are subscribed to the store with the newer version. Is there a way to restore the old functionality and have an option to only notify of updates from subscribed stores?

**Comment by marcodinissantos** [comment]
Thanks for your feedback CarbonFixer! We'll definitely look into it and keep you posted if we add this feature. We appreciate your input.

**Comment by analaragomes** [comment]
Hello, v8.3.0.0 of Aptoide only notifies you of updates from subscribed stores.
Thanks.
