### ISSUE TITLE
[Bug] Apps don't get updated {SOLVED}

### ISSUE THREAD

**Issue by frenchiveruti** [Aptoide/aptoide-client#5]
So. I've a Samsung Galaxy Core (Samsung I8260) with Aptoide v7.0.9 installed, and I'm having an issue when updating already installed apps, that they don't get updated, **instead, it flashes a white screen like it's opening something, and then closes**, I'm missing any app in my phone?
In the hardware information, it states:  
SDK version: 16  
Screen Size: 2  
ESGL version: 2.0  
CPU: Armeabe-v7a,armeabi  
Android: 4.1.2
Kernel: 3.4.0-1423170-user dpi@DELL152#1SMPPREEMPT (...)

**Comment by henriquedesousa** [comment]
Do you happen to have root on your device, but denied Aptoide access to it?

**Comment by frenchiveruti** [comment]
I have root, but aptoide doesn't seem to request it from me, i have super su as rooting app, is there a way to manually adding it to a root app?

**Comment by henriquedesousa** [comment]
Check in super su if Aptoide wasn't already denied access to root, sometimes it may be it. 
Then I could suggest you clean data/force stop or just plain uninstall/reinstall it, but it may be too much of an hassle.

**Comment by frenchiveruti** [comment]
Ok, so, I uninstalled both Aptoide and SuperSu, installed them again, and now it seems to work, thanks for the help.
